name: pannm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.4.0
  camera: ^0.10.0

dev_dependencies: 
  flutter_lints: ^3.0.2
  flutter_test: 
    sdk: flutter
    
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/black.jpg
    - assets/images/jeans.png
    - assets/images/Tshirt.png
    - assets/images/blackhood.jpg
    - assets/images/hawaii.jpg
    - assets/images/white.png
    - assets/images/ck.jpg
    - assets/images/crop.jpg
    - assets/images/cargo.jpg
    - assets/images/blue.jpg
    - assets/images/Red.png
    - assets/images/whitekid.png
    - assets/images/add.png

  fonts: 
    - family: Hina Mincho
      fonts: 
        - asset: assets/fonts/HinaMinchoRegular.ttf
          weight: 400
    - family: Ibarra Real Nova
      fonts: 
        - asset: assets/fonts/IbarraRealNovaRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/IbarraRealNovaRomanBold.ttf
          weight: 700
        - asset: assets/fonts/IbarraRealNovaRegular.ttf
          weight: 400
    - family: Hind
      fonts: 
        - asset: assets/fonts/HindRegular.ttf
          weight: 400

