// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6caoOI5rIJNyfloqHtPuHdFSv25K2vvo',
    appId: '1:304251364753:web:1cd62bcb63543384f4a630',
    messagingSenderId: '304251364753',
    projectId: 'mobileproject-e7d6e',
    authDomain: 'mobileproject-e7d6e.firebaseapp.com',
    storageBucket: 'mobileproject-e7d6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlZ6ykuCgxKpQcXxZh1l3nPYPqRilpd6M',
    appId: '1:304251364753:android:59789c825e16bc96f4a630',
    messagingSenderId: '304251364753',
    projectId: 'mobileproject-e7d6e',
    storageBucket: 'mobileproject-e7d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1jJBenDAEw4oeQtSW-0sreJN3LLHVhp8',
    appId: '1:304251364753:ios:3991c28bcd2f8ec2f4a630',
    messagingSenderId: '304251364753',
    projectId: 'mobileproject-e7d6e',
    storageBucket: 'mobileproject-e7d6e.appspot.com',
    iosBundleId: 'com.example.pannm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1jJBenDAEw4oeQtSW-0sreJN3LLHVhp8',
    appId: '1:304251364753:ios:3991c28bcd2f8ec2f4a630',
    messagingSenderId: '304251364753',
    projectId: 'mobileproject-e7d6e',
    storageBucket: 'mobileproject-e7d6e.appspot.com',
    iosBundleId: 'com.example.pannm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6caoOI5rIJNyfloqHtPuHdFSv25K2vvo',
    appId: '1:304251364753:web:cc7a35a21a5ee782f4a630',
    messagingSenderId: '304251364753',
    projectId: 'mobileproject-e7d6e',
    authDomain: 'mobileproject-e7d6e.firebaseapp.com',
    storageBucket: 'mobileproject-e7d6e.appspot.com',
  );
}
